CREATE DATABASE SQL_ECOMMERCE_PROJECT;

USE SQL_ECOMMERCE_PROJECT;

SELECT * FROM E_COMMERCE_SALES;

--TOTAL ORDERS
SELECT COUNT(QUANTITY) AS TOTAL_ORDERS
FROM E_COMMERCE_SALES 


--TOTAL SALES
SELECT SUM(SALES) AS TOTAL_SALES 
FROM E_COMMERCE_SALES 

--TOTAL PROFIT
SELECT SUM(PROFIT) AS TOTAL_PROFIT
FROM E_COMMERCE_SALES 


--SALES BY REGION
SELECT REGION,SUM(SALES) AS TOTAL_SALES
FROM E_COMMERCE_SALES 
GROUP BY REGION
ORDER BY TOTAL_SALES DESC


---PROFIT BY REGION
SELECT REGION,SUM(PROFIT) AS TOTAL_PROFIT
FROM E_COMMERCE_SALES 
GROUP BY REGION
ORDER BY TOTAL_PROFIT DESC


--SALES BY CATEGORY
SELECT CATEGORY ,SUM(SALES) AS TOTAL_SALES
FROM E_COMMERCE_SALES 
GROUP BY Category 
ORDER BY TOTAL_SALES


--PROFIT BY CATEGORY
SELECT CATEGORY ,SUM(PROFIT) AS TOTAL_PROFIT
FROM E_COMMERCE_SALES 
GROUP BY Category 
ORDER BY TOTAL_PROFIT


--MOST PROFITABLE SUBCATEGORY
SELECT CATEGORY ,SUM(PROFIT) AS TOTAL_PROFIT
FROM E_COMMERCE_SALES 
GROUP BY Category 
ORDER BY TOTAL_PROFIT DESC

--CITY WISE SALES(TOP 10)
SELECT TOP 10 
CITY,
SUM(SALES) AS TOTAL_SALES
FROM E_COMMERCE_SALES 
GROUP BY CITY
ORDER BY TOTAL_SALES DESC




--LOSS MAKING SUBCATEGORY
SELECT CATEGORY ,SUM(PROFIT) AS TOTAL_PROFIT
FROM E_COMMERCE_SALES 
GROUP BY Category 
HAVING SUM(PROFIT)<0


--TOP 10 SUB_CATEGORY SALES
SELECT TOP 10 SUB_CATEGORY,SUM(SALES) AS TOTAL_SALES
FROM E_COMMERCE_SALES 
GROUP BY SUB_CATEGORY
ORDER BY TOTAL_SALES DESC


--AVG DISCOUNT GIVEN
SELECT AVG(DISCOUNT) AS AVG_GIVEN
FROM E_COMMERCE_SALES 


--PROFIT MARGIN BY CATEGORY
SELECT 
CATEGORY,
SUM(SALES) AS TOTAL_SALES,
SUM(PROFIT) AS TOTAL_PROFIT,
(SUM(PROFIT)/SUM(SALES)*100)AS PROFIT_MARGIN
FROM E_COMMERCE_SALES 
GROUP BY CATEGORY

--SHIP MODE BY PROFIT
SELECT
SHIP_MODE,
SUM(PROFIT) AS TOTAL_PROFIT
FROM E_COMMERCE_SALES 
GROUP BY SHIP_MODE
ORDER BY TOTAL_PROFIT DESC

--SALES BY SEGMENT
SELECT SEGMENT,SUM(SALES) AS TOTAL_SALES
FROM E_COMMERCE_SALES 
GROUP BY SEGMENT





